/* eslint-disable react-hooks/rules-of-hooks */
import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useContext, useEffect, useState } from "react";
import { Layout } from "../layouts/dashboard/layout";
import QuillNoSSRWrapper from "../components/Editor";
import {
  Button,
  Card,
  CardActions,
  CardContent,
  Container,
  Box,
  TextField,
  Typography,
} from "@mui/material";
import ToasterContext from "@/utils/context/tosterContext";
const writeBlog = () => {
  const modules = {
    toolbar: [
      [{ header: [1, 2, 3, 4, 5, 6] }],
      [{ size: [] }],
      ["link", "image", "video"],
      ["bold", "italic", "underline", "strike", "blockquote", "CustomButton"],
      [
        { list: "ordered" },
        { list: "bullet" },
        { indent: "-1" },
        { indent: "+1" },
      ],
      ["clean"],
      [{ align: [] }],
      [{ color: [] }, { background: [] }],
    ],
    clipboard: {
      matchVisual: false,
    },
  };
  const formats = [
    "header",
    "font",
    "size",
    "bold",
    "italic",
    "underline",
    "strike",
    "blockquote",
    "list",
    "bullet",
    "indent",
    "link",
    "image",
    "video",
    "color",
    "background",
  ];
  const router = useRouter();
  const selectedBlog = router.query;
  console.log("selectedBlog", selectedBlog.data);
  const [textAreaData, setTextAreaData] = useState();
  const [title, setTitle] = useState("");
  const [loading, setLoading] = useState(false);
  const fireToasterContext = useContext(ToasterContext);

  // Check if blog and title exist in local storage
  useEffect(() => {
    const storedBlog = JSON.parse(localStorage.getItem("blog"));
    const storedTitle = JSON.parse(localStorage.getItem("title"));
    console.log("title", storedTitle);
    if (storedBlog && storedTitle) {
      setTextAreaData(storedBlog);
      setTitle(storedTitle);
    }
  }, []);

  const handleChange = (e) => {
    const editorData = e;
    setTextAreaData(editorData);
  };

  const handleUpdateBlog = async () => {
    const token = localStorage.getItem("token");
    setLoading(true);
    if (textAreaData === undefined) {
      alert("Please write a blog ");
      return;
    }

    let finalData = {
      data: {
        name: textAreaData,
        title: title,
      },
      status: "Published",
    };

    try {
      const response = await axios.patch(
        `${process.env.NEXT_PUBLIC_API_URL}/blog/${selectedBlog.data}`,
        finalData,
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );
      setLoading(false);

      fireToasterContext.fireToasterHandler(true, "Blog Created Successfully");
      router.push("/view-site");
      localStorage.removeItem("title");
      localStorage.removeItem("blog");

      console.log("publishing blog response", response.data);
    } catch (error) {
      console.error("Error publishing blog:", error);
      fireToasterContext.fireToasterHandler(false, "Something went wrong");
    }
  };

  const handlePreviewBlog = () => {
    localStorage.setItem("blog", JSON.stringify(textAreaData));
    localStorage.setItem("title", JSON.stringify(title));
    router.push("/preview-blog");
  };
  const handleBackButton = () => {
    router.push("/view-site");
    localStorage.removeItem("blog");
    localStorage.removeItem("title");
  };

  return (
    <Layout>
      <Head>
        <title>Write a New Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ height: "90vh" }}>
        <Container sx={{ mt: "110px" }}>
          <Button
            onClick={() => handleBackButton()}
            sx={{
              backgroundColor: "#40c1b9",
              color: "white",
              width: "135px",
              height: "42px",
              mr: 5,

              "&:hover": {
                boxShadow: 4,
                backgroundColor: "#40c1b9",
                color: "white",
              },
            }}
          >
            Back
          </Button>
          <Box sx={{ display: "flex", alignItems: "center" }}>
            <Box>
              <Typography
                variant="h4"
                sx={{
                  fontSize: "40px",
                  fontWeight: "bold",
                  pt: 2,
                  pb: 0,
                  textAlign: "right",
                  mb: 1,
                  mr: "122px",
                }}
              >
                {textAreaData ? "Edit Blog" : "Write Blog Here"}
              </Typography>
            </Box>
          </Box>

          <Card>
            <CardContent sx={{ maxHeight: "100%" }}>
              <Box sx={{ my: 2 }}>
                <TextField
                  fullWidth
                  placeholder="Add Title"
                  label="Blog Title"
                  value={title}
                  onChange={(event) => setTitle(event.target.value)}
                />
              </Box>

              <div id="scrolling-container" class="quill-editor">
                <div id="editor">
                  <QuillNoSSRWrapper
                    modules={modules}
                    formats={formats}
                    theme="snow"
                    value={textAreaData}
                    onChange={handleChange}
                    placeholder="Write Blog here..."
                    style={{ height: "450px" }}
                  />
                </div>
              </div>
            </CardContent>
            <CardActions
              sx={{ display: "flex", justifyContent: "flex-end", mt: 4 }}
            >
              <Button
                onClick={handlePreviewBlog}
                disabled={!textAreaData}
                sx={{
                  backgroundColor: "#40c1b9",
                  color: "white",
                  width: "135px",
                  height: "42px",
                  "&:hover": {
                    boxShadow: 4,
                    backgroundColor: "#40c1b9",
                    color: "white",
                  },
                }}
              >
                Preview Blog
              </Button>
              <Button
                onClick={() => handleUpdateBlog()}
                disabled={!textAreaData}
                sx={{
                  backgroundColor: "#40c1b9",
                  color: "white",
                  width: "135px",
                  height: "42px",
                  "&:hover": {
                    boxShadow: 4,
                    backgroundColor: "#40c1b9",
                    color: "white",
                  },
                }}
              >
                {loading ? "Loading..." : "Publish"}
              </Button>
            </CardActions>
          </Card>
        </Container>
      </main>
    </Layout>
  );
};
export default writeBlog;
