import React, { useEffect, useState } from "react";
import { Layout } from "@/layouts/dashboard/layout";
import Head from "next/head";
import Container from "@mui/material/Container";
import { Box, Button } from "@mui/material";
import { useRouter } from "next/router";

const PreviewBlog = () => {
  const router = useRouter();
  const selectedBlog = router.query;
  console.log("preivw blod", selectedBlog.data);
  const [getBlog, setBlog] = useState();
  const [getTitle, setTitle] = useState();

  useEffect(() => {
    setBlog(JSON.parse(localStorage.getItem("blog")));
    setTitle(JSON.parse(localStorage.getItem("title")));
  }, []);

  // Function to sanitize the HTML content to prevent XSS attacks
  const createMarkup = (html) => {
    return { __html: html };
  };

  const handleBackButton = () => {
    router.push("/view-site");
    localStorage.removeItem("blog");
    localStorage.removeItem("title");
  };

  return (
    <Layout>
      <Head>
        <title>Blog preview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ height: "90vh" }}>
        <Container maxWidth="md" sx={{ mt: "110px" }}>
          <Box sx={{ mb: 3 }}>
            <Button
              onClick={() => handleBackButton()}
              sx={{
                backgroundColor: "#40c1b9",
                color: "white",
                width: "135px",
                height: "42px",
                mr: 5,

                "&:hover": {
                  boxShadow: 4,
                  backgroundColor: "#40c1b9",
                  color: "white",
                },
              }}
            >
              Back
            </Button>
          </Box>
          <h1>{getTitle}</h1>
          {/* Render the HTML content safely */}
          <div dangerouslySetInnerHTML={createMarkup(getBlog)} />
        </Container>
      </main>
    </Layout>
  );
};

export default PreviewBlog;
