/* eslint-disable react-hooks/rules-of-hooks */
import React from "react";
import { Layout } from "../layouts/dashboard/layout";
import Head from "next/head";
import {
  Button,
  Container,
  SvgIcon,
  Typography,
  Box,
  IconButton,
  TableContainer,
  Table,
  TableHead,
  TableRow,
  TableCell,
  TableBody,
} from "@mui/material";
import MoreHorizIcon from "@mui/icons-material/MoreHoriz";
import styles from "@/styles/ViewSite.module.css";
import { useRouter } from "next/router";

const viewSite = () => {
  const router = useRouter();
  return (
    <Layout>
      <Head>
        <title>view site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container sx={{ mt: "108px" }}>
          <TableContainer sx={{ maxHeight: 620 }}>
            <Table stickyHeader aria-label="sticky table">
              <TableHead>
                <TableRow>
                  <TableCell>
                    <Typography className={styles.typo}>Title</Typography>
                  </TableCell>
                  <TableCell>
                    <Typography className={styles.typo}>Status</Typography>
                  </TableCell>
                  <TableCell>
                    <Typography className={styles.typo}>Stats</Typography>
                  </TableCell>
                  <TableCell sx={{ textAlign: "end" }}>
                    <Button
                      onClick={() => router.push("/write-blog")}
                      variant="contained"
                      className={styles.btnText}
                      sx={{
                        backgroundColor: "#40c1b9",
                        color: "white",
                      }}
                      startIcon={
                        <SvgIcon fontSize="small">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="20"
                            height="20"
                            viewBox="0 0 20 20"
                            fill="none"
                          >
                            <path
                              d="M10 15.8333L15.8333 10L18.3333 12.5L12.5 18.3333L10 15.8333Z"
                              stroke="#FFFCFE"
                              stroke-linecap="round"
                              stroke-linejoin="round"
                            />
                            <path
                              d="M15 10.8334L13.75 4.58335L1.66666 1.66669L4.58332 13.75L10.8333 15L15 10.8334Z"
                              stroke="#FFFCFE"
                              stroke-linecap="round"
                              stroke-linejoin="round"
                            />
                            <path
                              d="M1.66666 1.66669L7.98832 7.98835"
                              stroke="#FFFCFE"
                              stroke-linecap="round"
                              stroke-linejoin="round"
                            />
                            <path
                              d="M9.16667 10.8333C10.0871 10.8333 10.8333 10.0871 10.8333 9.16667C10.8333 8.24619 10.0871 7.5 9.16667 7.5C8.24619 7.5 7.5 8.24619 7.5 9.16667C7.5 10.0871 8.24619 10.8333 9.16667 10.8333Z"
                              stroke="#FFFCFE"
                              stroke-linecap="round"
                              stroke-linejoin="round"
                            />
                          </svg>
                        </SvgIcon>
                      }
                    >
                      Add New
                    </Button>
                  </TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                <TableRow>
                  <TableCell sx={{ border: "none" }}></TableCell>
                </TableRow>
                <TableRow sx={{ backgroundColor: "#F7FAFC" }}>
                  <TableCell sx={{ my: 2, height: 100, border: "none" }}>
                    <Typography className={styles.card_heading_typo}>
                      Design: A Survival Guide for Beginners
                    </Typography>
                    <Typography className={styles.card_sub_heading_typo}>
                      Posted 3 days ago
                    </Typography>
                  </TableCell>
                  <TableCell sx={{ my: 2, border: "none" }}>
                    <Button className={styles.card_btn}>published</Button>
                  </TableCell>
                  <TableCell sx={{ my: 2, border: "none" }}>
                    {/* stats wrapper */}
                    <Box className={styles.stats_wrapper}>
                      <Typography className={styles.stats}>120</Typography>
                      <Typography className={styles.stats_views}>
                        views
                      </Typography>
                      <SvgIcon>
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          width="24"
                          height="24"
                          viewBox="0 0 24 24"
                          fill="none"
                        >
                          <path
                            d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z"
                            stroke="#9AE6B4"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                          <path
                            d="M16 12L12 8L8 12"
                            stroke="#9AE6B4"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                          <path
                            d="M12 16V8"
                            stroke="#9AE6B4"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                        </svg>
                      </SvgIcon>
                    </Box>
                  </TableCell>
                  <TableCell sx={{ textAlign: "end", my: 2, border: "none" }}>
                    <IconButton>
                      <MoreHorizIcon />
                    </IconButton>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell sx={{ border: "none" }}></TableCell>
                </TableRow>
                <TableRow sx={{ backgroundColor: "#F7FAFC" }}>
                  <TableCell sx={{ my: 2, height: 100, border: "none" }}>
                    <Typography className={styles.card_heading_typo}>
                      Design: A Survival Guide for Beginners
                    </Typography>
                    <Typography className={styles.card_sub_heading_typo}>
                      Posted 3 days ago
                    </Typography>
                  </TableCell>
                  <TableCell sx={{ my: 2, border: "none" }}>
                    <Button className={styles.card_btn}>published</Button>
                  </TableCell>
                  <TableCell sx={{ my: 2, border: "none" }}>
                    {/* stats wrapper */}
                    <Box className={styles.stats_wrapper}>
                      <Typography className={styles.stats}>120</Typography>
                      <Typography className={styles.stats_views}>
                        views
                      </Typography>
                      <SvgIcon>
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          width="24"
                          height="24"
                          viewBox="0 0 24 24"
                          fill="none"
                        >
                          <path
                            d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z"
                            stroke="#9AE6B4"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                          <path
                            d="M16 12L12 8L8 12"
                            stroke="#9AE6B4"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                          <path
                            d="M12 16V8"
                            stroke="#9AE6B4"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                        </svg>
                      </SvgIcon>
                    </Box>
                  </TableCell>
                  <TableCell sx={{ textAlign: "end", my: 2, border: "none" }}>
                    <IconButton>
                      <MoreHorizIcon />
                    </IconButton>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell sx={{ border: "none" }}></TableCell>
                </TableRow>
                <TableRow sx={{ backgroundColor: "#F7FAFC" }}>
                  <TableCell sx={{ my: 2, height: 100, border: "none" }}>
                    <Typography className={styles.card_heading_typo}>
                      Design: A Survival Guide for Beginners
                    </Typography>
                    <Typography className={styles.card_sub_heading_typo}>
                      Posted 3 days ago
                    </Typography>
                  </TableCell>
                  <TableCell sx={{ my: 2, border: "none" }}>
                    <Button className={styles.card_btn}>published</Button>
                  </TableCell>
                  <TableCell sx={{ my: 2, border: "none" }}>
                    {/* stats wrapper */}
                    <Box className={styles.stats_wrapper}>
                      <Typography className={styles.stats}>120</Typography>
                      <Typography className={styles.stats_views}>
                        views
                      </Typography>
                      <SvgIcon>
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          width="24"
                          height="24"
                          viewBox="0 0 24 24"
                          fill="none"
                        >
                          <path
                            d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z"
                            stroke="#9AE6B4"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                          <path
                            d="M16 12L12 8L8 12"
                            stroke="#9AE6B4"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                          <path
                            d="M12 16V8"
                            stroke="#9AE6B4"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                        </svg>
                      </SvgIcon>
                    </Box>
                  </TableCell>
                  <TableCell sx={{ textAlign: "end", my: 2, border: "none" }}>
                    <IconButton>
                      <MoreHorizIcon />
                    </IconButton>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell sx={{ border: "none" }}></TableCell>
                </TableRow>
                <TableRow sx={{ backgroundColor: "#F7FAFC" }}>
                  <TableCell sx={{ my: 2, height: 100, border: "none" }}>
                    <Typography className={styles.card_heading_typo}>
                      Design: A Survival Guide for Beginners
                    </Typography>
                    <Typography className={styles.card_sub_heading_typo}>
                      Posted 3 days ago
                    </Typography>
                  </TableCell>
                  <TableCell sx={{ my: 2, border: "none" }}>
                    <Button className={styles.card_btn}>published</Button>
                  </TableCell>
                  <TableCell sx={{ my: 2, border: "none" }}>
                    {/* stats wrapper */}
                    <Box className={styles.stats_wrapper}>
                      <Typography className={styles.stats}>120</Typography>
                      <Typography className={styles.stats_views}>
                        views
                      </Typography>
                      <SvgIcon>
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          width="24"
                          height="24"
                          viewBox="0 0 24 24"
                          fill="none"
                        >
                          <path
                            d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z"
                            stroke="#9AE6B4"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                          <path
                            d="M16 12L12 8L8 12"
                            stroke="#9AE6B4"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                          <path
                            d="M12 16V8"
                            stroke="#9AE6B4"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                        </svg>
                      </SvgIcon>
                    </Box>
                  </TableCell>
                  <TableCell sx={{ textAlign: "end", my: 2, border: "none" }}>
                    <IconButton>
                      <MoreHorizIcon />
                    </IconButton>
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </TableContainer>
        </Container>
      </main>
    </Layout>
  );
};
export default viewSite;
