/* eslint-disable react-hooks/rules-of-hooks */
import Head from "next/head";
import React, { useState } from "react";
import { Layout } from "../layouts/dashboard/layout";
import { Container } from "@mui/material";
import SunEditor from "../components/SunEditor";

const writeBlog = () => {
  return (
    <Layout>
      <Head>
        <title>Write a New Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ height: "90vh" }}>
        <Container sx={{ mt: "110px" }}>
          <SunEditor />
        </Container>
      </main>
    </Layout>
  );
};
export default writeBlog;
